apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb
  labels:
    app.kubernetes.io/name: ycsb
spec:
  replicas: 12
  selector:
    matchLabels:
      app.kubernetes.io/name: ycsb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ycsb
    spec:
      containers:
        - name: ycsb
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: "1"
              memory: "128Mi"
          env:
            - name: TIGRIS_URL
              value: "tigris-grpc:80"
            - name: TIGRIS_POSTFIX_TESTDB
              value: "1"
            - name: LOADTHREADCOUNT
              value: "4"
            - name: ENGINE
              value: "tigris"
            - name: RUNMODE
              value: "multiple_threads"
            - name: RUNTHREADDURATION
              value: "1h"
            - name: RUNTHREADSLEEPINTERVAL
              value: "1s"
            - name: RECORDCOUNT
              # for in-memory
              value: "1000000"
              # for on-disk
              # value: "1000000"
            - name: DROPANDLOAD
              value: "1"
            - name: READPROPORTION
              value: "1.0"
            - name: UPDATEPROPORTION
              value: "0"
            - name: SCANPROPORTION
              value: "0"
            - name: RUNTHREADCONF
              value: "1"
            - name: FIELDCOUNT
              value: "10"
            - name: FIELDLENGTH
              value: "380"
            - name: MAXSCANLENGTH
              value: "20"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /mnt/fdb-config-volume
              name: fdb-cluster-config-volume
            - mountPath: /etc/tigrisdata/tigris
              name: server-config-volume
          image: "tigrisdata/ycsb:master" 
          imagePullPolicy: IfNotPresent
          command:
            - "/run.sh"
      volumes:
        - name: tmp
          emptyDir: {}
        # This configmap is created by the fdb-kubernetes-operator when the cluster is created
        # The cluster-name below has to be replaced with the actual cluster name during kustomization phase
        - name: fdb-cluster-config-volume
          configMap:
            name: fdb-cluster-config
        # This configmap is created during the kustomization phase
        - name: server-config-volume
          configMap:
            name: tigris-server-config
