apiVersion: v1
kind: ServiceAccount
metadata:
  name: typesense-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: typesense-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: typesense-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: typesense-role
subjects:
  - kind: ServiceAccount
    name: typesense-service-account
