apiVersion: v1
kind: ConfigMap
metadata:
  name: check-ready
  labels:
    app.kubernetes.io/instance: tigris-search
data:
  check_ready.sh: |
    #!/usr/bin/env bash

    TSHOST=localhost
    TSPORT={{ .Values.api_port }}

    INFO=$(curl -s ${TSHOST}:${TSPORT}/health)
    echo "${INFO}" | egrep '"ok":true'
    RETCODE=$?
    if [ ${RETCODE} -gt 0 ]; then
        echo "/health endpoint responded with ${INFO}"
    fi
    exit ${RETCODE}
---
apiVersion: v1
data:
  initial-nodes: tigris-search-0.ts:{{ .Values.peering_port }}:{{ .Values.api_port }}
kind: ConfigMap
metadata:
  name: setup
  labels:
    app.kubernetes.io/instance: tigris-search
