apiVersion: v2
name: tigris-stack
description: Tigris Stack
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: fdb-operator
    version: 0.2.0
    repository: file://../fdb-operator
  - name: fdb-cluster
    version: 0.1.0
    repository: file://../fdb-cluster
  - name: tigris-search
    version: 0.1.0
    repository: file://../tigris-search
  - name: ingress-nginx
    version: 4.3.0
    repository: https://kubernetes.github.io/ingress-nginx
  - name: tigris-server
    version: 0.1.0
    repository: file://../tigris-server
