# Copyright 2022 Tigris Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### FoundationDB Cluster related settings
fdb-cluster:
  usable_regions: 1

  processCounts: 
    storage: 4
    log: 4

  databaseConfiguration:
    storage: 4
    logs: 4
    
  redundancy_mode: double

  resources:
    requests:
      cpu: "100m"
      memory: "4Gi"
    limits:
      cpu: "1"
      memory: "8Gi"

  volumeClaim:
    resources:
      requests:
        storage: "10Gi"

  failureDetectionTimeSeconds: 300
  replaceInstancesWhenResourcesChange: true
  automationOptions:
    replacements:
      enabled: true

### Tigris Search related settings
tigris-search:
  image: tigrisdata/typesense:latest

  ### API port, servicing requests
  api_port: 8108

  ### Peering port, used between the nodes to communicate with each other
  peering_port: 8107

  ### How much storage to allocate
  storage: "10Gi"

  ### Number of replicas
  replicas: 3

  ### Resources to allocate
  resources:
    limits:
      cpu: "1"
      memory: "4Gi"
    requests:
      cpu: "1"
      memory: "4Gi"

### Tigris Server related settings
tigris-server:
  image: tigrisdata/tigris:1.0.0-beta.35

  # Port allocated to the Tigris API
  api_port: 8080

  # High level service port
  service_port: 80

  # Only logs every y request
  log_sample_rate: 0.0001

  # Only trace every x call
  trace_sample_rate: 0.0001

  tracing:
    enabled: false
    
  # The number of Pods serving requests
  replicas: 6

  # Resources
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

victoria-metrics-single:
  enabled: true
  configMap: scrapeconfig
  server:
    scrape:
      enabled: true
      configMap: scrapeconfig

grafana:
  enabled: true
  extraInitContainers:
    - name: waitfor-victoriametrics
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          'until nc -vz tigris-stack-victoria-metrics-single-server.default 8428 ; do echo "Waiting for victoriametrics..."; sleep 3; done;',
        ]
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: victoriametrics
          type: prometheus
          orgId: 1
          url: http://tigris-stack-victoria-metrics-single-server.default:8428
          access: proxy
          isDefault: true
          updateIntervalSeconds: 10
          editable: true

  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: true
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      victoriametrics:
        gnetId: 10229
        revision: 22
        datasource: victoriametrics
      kubernetes:
        gnetId: 14205
        revision: 1
        datasource: victoriametrics

ingress-nginx:
  enabled: true

ycsb:
  enabled: true

metrics-server:
  enabled: true
  defaultArgs:
    - --kubelet-insecure-tls
    - --cert-dir=/tmp
